baseurl = "https://www.mangregory.me"
title = "mangregory"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
  author = "Gregory Manitaras"
  info = "(Integrated) Computer Science Senior Fresher"
  description = "Gregory Manitaras's personal website"
  keywords = "developer,personal"
  avatarurl = "images/aal_grad.png"
  #gravatar = "john.doe@example.com"

  favicon_32 = "images/favicon-32x32.png"
  favicon_16 = "images/favicon-16x16.png"

  since = 2022

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/mangregory128/"
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 2
  url = "https://linkedin.com/in/grigoris-manitaras-48491723a/"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/manitarasg/"
[[params.social]]
  name = "YouTube"
  icon = "fa fa-youtube fa-2x"
  weight = 4
  url = "https://youtube.com/@mangregory/"

# Menu links
[[menu.main]]
  name = "Projects"
  weight = 2
  url  = "projects/"
[[menu.main]]
  name = "About"
  weight = 1
  url = "about/"