baseurl = "https://www.mangregory.me"
title = "Gregory Manitaras"
theme = ["hugo-embed-pdf-shortcode", "hugo-coder"]
languagecode = "en"
defaultcontentlanguage = "en"

pagination.pagerSize = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
  author = "Gregory Manitaras"
  info = "Computer Science Senior Sophister, TCD"
  description = "Gregory Manitaras's personal website"
  keywords = "developer,personal"
  avatarurl = "images/Gregory-crop.jpg"
  #gravatar = "john.doe@example.com"

  favicon_32 = "images/favicon-32x32.png"
  favicon_16 = "images/favicon-16x16.png"

  since = 2022

  enableTwemoji = true
  enableInlineShortcodes = true
  mainSections = ["projects"]
  colorScheme = "auto"
  hidecolorschemetoggle = false

  customCSS = ["css/style.css"]
  # customSCSS = ["scss/custom.scss"]
  customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/mangregory128/"
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 2
  url = "https://linkedin.com/in/grigoris-manitaras/"
[[params.social]]
  name = "YouTube"
  icon = "fa fa-youtube fa-2x"
  weight = 4
  url = "https://youtube.com/@mangregory/"

# Menu links
[[menu.main]]
  name = "Experience"
  weight = 2
  url  = "projects/"
[[menu.main]]
  name = "About"
  weight = 1
  url = "about/"